backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: food
    label: "Food Item" # Used in the UI, ie.: "New Post"
    folder: "content/food" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "poultry"}
      - {label: "Prices", name: "prices", widget: "list", default: [5, 10]}
      - {label: "Sizes", name: "sizes", widget: "list", default: ["small", "large"]}
      - {label: "Spicy", name: "spicy", widget: "boolean"}